#!/usr/bin/env python3

import serial

port_str = '/dev/ttyACM0'

if __name__ == '__main__':
    ser = serial.Serial(port_str,9600,timeout=5)
    ser.flush()

    while(True):
        strain_val = []
        if ser.in_waiting > 0:
            line = ser.readline().decode('utf-8').rstrip()
            print(line)
            strain_val = line.split(':')
        for idx, val in enumerate(strain_val,start=1):
            print("Strain {:d} has {:s}".format(idx,val))
